version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - '9999:5432' # Map 9999 on the host to 5432 inside the container
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: nest_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
