
POST http://localhost:3300/users
Content-Type: application/json
{
    "firstName": "Jon",
    "lastName": "Doe",
    "email": "jon@email.com",
    "password": "jon1234"
}

POST http://localhost:3300/users/1234
Content-Type: application/json
{
    "firstName": "Jon3",
    "lastName": "Doe3",
    "email": "jon3@email9.com",
    "password": "Jon$1234"
}

POST http://localhost:3300/users/express
Content-Type: application/json
{
    "firstName": "Jon",
    "lastName": "Doe",
    "email": "jon@email.com",
    "password": "jon1234"
}

POST http://localhost:3300/users/create-many
Content-Type: application/json
{
    "users": [
  {
    "firstName": "Jon11",
    "lastName": "Doe11",
    "email": "Jon@email11.com",
    "password": "Jon#1234213123"
  },
   {
    "firstName": "Jon22",
    "lastName": "Doe22",
    "email": "jon@email22.com",
    "password": "Jon#123412313"
  },
   {
    "firstName": "Jon33",
    "lastName": "Doe33",
    "email": "jon@email33.com",
    "password": "Jon#123412313"
  }
 ]
}